//As per MSK p. 47-48
const originalItemFeatures = [
    "Ablenkend",
    "Auslöser",
    "Deckung",
    "Defensiv",
    "Detonation",
    "Doppelwaffe",
    "Dornen",
    "Durchdringung",
    "Entwaffnend",
    "Entwaffnungsimmunität",
    "Entwaffnungsschutz",
    "Exakt",
    "Ferndistanz",
    "Freihändig",
    "Gehärtet",
    "Improvisiert",
    "Kälteschutz",
    "Kletterhilfe",
    "Kritisch",
    "Lange Waffe",
    "Nahkampftauglich",
    "Paarwaffe",
    "Parierwaffe",
    "Primitiv",
    "Reiterrüstung",
    "Reiterschild",
    "Reiterwaffe",
    "Rückkehrend",
    "Rückstoß",
    "Schadensschwund",
    "Scharf",
    "Schildwall",
    "Stabil",
    "Behinderung",
    "Standfestigkeit",
    "Stumpf",
    "Teilbar",
    "Treffsicher",
    "Umklammern",
    "Umwerfend",
    "Unauffällig",
    "Unhandlich",
    "Vielseitig",
    "Wattiert",
    "Wuchtig",
    "Wurffähig",
    "Wurfkörper",
    "Zerbrechlich",
    "Zweihändig"
] as const ;

// As per MSK p. 90-92
const itemImprovements = [
    "Bequem",
    "Dornen",
    "Erhöhte Härte",
    "Erhöhte Schadensreduktion",
    "Erhöhter Waffenschaden",
    "Gehärtet",
    "Geheimfach",
    "Haleterung",
    "Hochwertige Fertigung",
    "Ferndistanz",
    "Fertigkeitsbonus",
    "Kälteschutz",
    "Paarwaffe",
    "Reduzierte Behinderung",
    "Reduzierter Tick-Zuschlag",
    "Reduzierte Last",
    "Reduzierte Waffengeschwindigkeit",
    "Schmutzabweisend",
    "Treffsicher",
    "Unauffällig",
    "Schutz vor Schadensarten",
    "Verbesserte Defensive",
    "Verbesserte Exaktheit",
    "Verbesserte Schärfe",
    "Verbesserter Entwaffnungsschutz",
    "Wasserfest",
    "Verbesserter Kritischer Schaden",
    "Verbessertes Ablenken",
    "Zerlegbar",
] as const

export const itemFeatures = Array.from(new Set([...originalItemFeatures,...itemImprovements])) as ItemFeature[];
export type ItemFeature = typeof originalItemFeatures[number] | typeof itemImprovements[number];