name: Release new Splittermond version
permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (without v prefix)'
        required: true

jobs:
  release-new-version:
    runs-on: ubuntu-latest
    env:
      outputName: splittermond-${{github.event.inputs.version}}
      outputFile: splittermond-${{github.event.inputs.version}}.zip
      prefixedVersion: v${{github.event.inputs.version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set new version in system.json
        run: node ./.github/scripts/index.cjs
        env:
          fileToUpdate: './public/system.json'
          version: ${{github.event.inputs.version}}

      - name: Set new version in package.json
        run: node ./.github/scripts/index.cjs
        env:
          fileToUpdate: './package.json'
          version: ${{github.event.inputs.version}}

      - name: Set new paths in System.json
        run: node ./.github/scripts/replace_links.cjs
        env:
          fileToUpdate: './public/system.json'
          newManifest: https://github.com/${{github.repository}}/releases/download/${{env.prefixedVersion}}/system.json
          newDownload: https://github.com/${{github.repository}}/releases/download/${{env.prefixedVersion}}/${{env.outputFile}}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Zip for Foundry
        run: |
          sudo apt-get install zip 
          cd dist/ && zip -r ../${{env.outputFile}} ./*; cd -
          zip -r ${{env.outputFile}} README.md FoundryModule1.png screenshots

      - name: Upload release assets
        uses: softprops/action-gh-release@v2.3.2
        with:
          generate_release_notes: true
          draft: false
          tag_name: v${{github.event.inputs.version}}
          files: |
            ${{env.outputFile}}
            dist/system.json
